spring.application.name=webprac
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/airline_bookings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
db.username=postgres
db.password=postgres